# Change these first
owner: gripfastistech # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Grip Fast Information Systems & Technology 
    url: https://gripfastistech.com
    icon: https://gripfastistech.com/templates/purity_iii/favicon.ico
  - name: Grip Fast Artworks
    url: https://gripfastart.works
    icon: https://gripfastart.works/images/icon.ico
  - name: B-K Lighting, Inc.
    url: https://bklighting.com
    icon: https://bklighting.com/templates/bklighting/favicon.ico
  - name: TEKA Illumination
    url: https://tekaillumination.com
    icon: https://tekaillumination.com/templates/tekaillumination/favicon.ico
  - name: DLC
    url: http://64.166.54.199:6201/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://gripfastistech.com/images/gryphon_background.svg
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Real-time and historical data on system performance.
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Home
      href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
  css:
    ".chartjs-render-monitor { filter: hue-rotate(-167deg) saturate(136.5%) brightness(80%); }
    body { background-color: #000000; color: darkgrey; }
    article { background-color: var(--color-dark1); }
    nav.svelte-1pyc7i4.svelte-1pyc7i4, nav.svelte-1sgaob0.svelte-1sgaob0 { background: #000000; border-bottom: 1px solid silver; }"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  # footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  footer: Brought to you with &#128420; by [gripfastistech.com](gripfastistech.com), &#128268; by [Upptime](https://upptime.js.org)
